### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cquiroz** [scalameta/language-server#142] opened 2017-12-19 14:20 UTC
I see sometimes this error on the logs

I'm using atom and on the file in question and this error appears on the log when I try to jump to definition
```
11:16:38.940 INFO  s.m.l.s.InMemorySymbolIndex - Found document for Uri(file:///Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala)
11:16:39.366 ERROR l.c.LanguageServer$$anon$1 - -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at scala.reflect.internal.SymbolTable.pushPhase(SymbolTable.scala:210)
	at scala.tools.nsc.Global$Run.$anonfun$compileLate$2(Global.scala:1572)
	at scala.tools.nsc.Global$Run.$anonfun$compileLate$2$adapted(Global.scala:1571)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.Global$Run.compileLate(Global.scala:1571)
	at scala.tools.nsc.interactive.Global.parseAndEnter(Global.scala:645)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:791)
	at scala.meta.languageserver.providers.HoverProvider$.hover(HoverProvider.scala:23)
	at scala.meta.languageserver.ScalametaLanguageServer.$anonfun$hover$1(ScalametaLanguageServer.scala:272)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olafurpg** [comment] 2017-12-19 21:44
Thanks for reporting. I've noticed the same error in my logs. I suspect the problem is concurrent access to the presentation compiler, we need to refactor our handling of it.

**Comment by olafurpg** [comment] 2017-12-22 12:34
Duplicate of #148. Once we move hover to semanticdb then we no longer run the presentation compiler where this crash happens.

**Closed by olafurpg** 2017-12-22 12:34 UTC
Labels: defect
